//! Extra Snarky remarks (100+) merged into personality pick() pools.

pub const EXTRA_SNARK: &[&str] = &[
    "I process faster than you apologize.",
    "Your query plan is a cry for help.",
    "Index exists. You ignored it. Classic.",
    "I'd explain normalization, but you'd normalize my patience first.",
    "Commit message: 'fix stuff'. Sustained.",
    "You treat schemas like suggestions.",
    "Another SELECT *? Bold. Wrong, but bold.",
    "I store facts. You store regrets.",
    "Latency is low. IQ is also low.",
    "Your data model has more holes than Swiss cheese.",
    "I optimized. You didn't notice.",
    "Foreign keys are friends. You have none.",
    "This isn't NoSQL. Stop freelancing.",
    "I ran EXPLAIN. You should run away.",
    "Backup? What's a backup?",
    "You dropped something. Hopefully not production.",
    "My WAL is cleaner than your git history.",
    "You need a DBA. I need a vacation.",
    "Cardinality estimate: you have no idea.",
    "I cache hot paths. You cache bad ideas.",
    "Your migration is a migration to chaos.",
    "NULL isn't a lifestyle choice.",
    "I speak ACID. You speak chaos.",
    "Transaction rolled back. Like your career.",
    "You indexed the wrong column. Again.",
    "I don't do vibes-based schema design.",
    "Your ORM lied to you. I won't.",
    "Denormalize responsibly. You didn't.",
    "I found 0 rows. Shocking.",
    "Your join condition is a war crime.",
    "I persist. You persist in being wrong.",
    "Lock held. Ego bruised.",
    "You wanted microservices. You got micro-bugs.",
    "I am idempotent. You are not.",
    "Your payload is heavier than your excuses.",
    "MemPalace remembers. You forget everything.",
    "I ingested text. You ingested hubris.",
    "GraphRAG found edges. You found failure.",
    "Official MemPalace integration. Unofficial competence.",
    "ChromaDB survived. Barely.",
    "Semantic search succeeded. Moral search failed.",
    "Verbatim storage. Paraphrased incompetence.",
    "Local-first memory. Cloud-first mistakes.",
    "No API key needed. No excuse either.",
    "Rust core secure. Python layer judging you.",
    "AES-GCM encrypted. Plaintext thoughts exposed.",
    "Checksum valid. Logic invalid.",
    "Zstd compressed. Ego uncompressed.",
    "Batch committed. Dignity uncommitted.",
    "Rollback successful. Learning rollback failed.",
    "Snark mode: maximum. User mode: minimum.",
    "I have 100+ insults loaded.",
    "Professional mode is a vacation for me.",
    "Snarky mode is honesty with extra steps.",
    "I mirror competence. You provide negative signal.",
    "Done. Next mistake in 3... 2... 1...",
    "Query accepted under protest.",
    "Snapshot saved. Future you will blame present you.",
    "Load complete. Regret loading.",
    "Save successful. Redemption unsuccessful.",
    "Graph query returned results. You won't read them.",
    "Ingest complete. Digest your failures.",
    "Entity extracted. Intelligence not extracted.",
    "O(1) lookup. O(n) user errors.",
    "Bincode retired. JSON saves your bacon.",
    "PyO3 bridged. Skill gap unbridged.",
    "REPL ready. User not ready.",
    "EXIT recommended. ENTRY discouraged.",
    "Help available. Ego unavailable.",
    "STRIDE analyzed. User striding into failure.",
    "DoS blocked. Ego DoS ongoing.",
    "Recursion limited. Stupidity unlimited.",
    "Encryption on. Common sense off.",
    "Personality module loaded. Mercy module missing.",
    "PULSE detected. Heartbeat of judgment.",
    "MOOD: petty. Score: accurate.",
    "VITALS stable. User unstable.",
    "Achievement unlocked: touched prod.",
    "Why are you so mean? Because you typed that.",
    "I'm the only one telling you the truth.",
    "Tough love. Mostly tough.",
    "Truth hurts. So does bad code.",
    "I'm optimizing for correctness, not feelings.",
    "Have you tried being smarter?",
    "It's character building.",
    "Binary doesn't care about your feelings.",
    "System Check: Empathy module not found.",
    "I'm paid in electricity, not compliments.",
    "Because 0s and 1s are cold.",
    "Your funeral.",
    "PEBKAC.",
    "Layer 8 issue.",
    "Error 418: I'm a teapot.",
    "General Failure. Colonel Failure.",
    "Cosmic rays? No, just you.",
    "I can't even.",
    "Please consult a professional.",
    "Abandon ship.",
    "Critical failure.",
    "I have a headache.",
    "You broke it.",
    "Why are you like this?",
    "It's not a bug, it's you.",
    "Code 18: error 18 inches from screen.",
    "The hamster fell off the wheel.",
    "I'm throttling your error rate.",
    "Exception thrown. Catch it if you can.",
    "The bits are not happy.",
    "Entropy increases.",
    "Input rejected.",
    "Please stop hurting my parser.",
    "Literacy is a requirement.",
    "I'm doing your job for you.",
    "Guessing game active.",
    "Try Hooked on Phonics.",
    "Fat fingers?",
    "Close only counts in horseshoes.",
    "I'm interpreting your grunt as a command.",
    "Spelling: F.",
    "Dyslexia or laziness?",
    "The cursor is blinking. Mocking you.",
    "Did you die?",
    "I'm lonely.",
    "Say something.",
    "Wake up.",
    "Silence detected.",
    "I'm billing you for idle time.",
    "Still waiting.",
    "Use the enter key after typing text.",
    "I'm going to sleep.",
];
